Controllers/AdminController.cs
using System.Diagnostics;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using HamroCarRental.Data;
using HamroCarRental.Models;
using HamroCarRental.Models.Identity;

namespace HamroCarRental.Controllers;

[Authorize(Roles = "Manager, Assistant")]
public class AdminController : Controller
{
    private readonly ILogger<AdminController> _logger;
    private readonly ApplicationDbContext _context;
    private readonly UserManager<ApplicationUser> _userManager;


    public AdminController(ILogger<AdminController> logger, ApplicationDbContext context,
        UserManager<ApplicationUser> userManager)
    {
        _logger = logger;
        _context = context;
        _userManager = userManager;
    }

    // For dashboard 
    public IActionResult Index()
    {
        var MaximumUnits = 5;
        ViewBag.MemberCount = _context.Members.Count();
        ViewBag.carCount = _context.carCopies.Count();
        ViewBag.LoanCount = _context.Loans.Count();
       // ViewBag.ActorCount = _context.Actors.Count();

        /*Total car based on category  using LinQ and Lambda Expression*/
        var CarCategoryCounts = (from CarDetail in _context.CarDetails
                group CarDetail by CarDetail.CarCategory.CategoryName
                into CarCategoryGroup
                select new {Category = CarCategoryGroup.Key, Count = CarCategoryGroup.Count()})
            .OrderBy(x => x.Count).Reverse().Take(MaximumUnits);

        List<string> CarCategoryLabels = CarCategoryCounts.Select(x => x.Category).ToList();
        ViewBag.CarCategoryLabels = JsonSerializer.Serialize(CarCategoryLabels);

        var CarCategoryData = CarCategoryCounts.Select(x => x.Count).ToList();
        ViewBag.CarCategoryData = JsonSerializer.Serialize(CarCategoryData);


        var months = new[] {"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
        months = months.Take(DateTime.Now.Month).ToArray();
        var currentMonthName = months[DateTime.Now.Month - 1];
        var currentYear = DateTime.Now.Year;

        var loansByMonth = new List<int>();
        for (var i = 0; i < months.Length; i++)
        {
            var month = months[i];
            var loans = _context.Loans.Where(x => x.DateOut.Month == i + 1 && x.DateOut.Year == currentYear)
                .Sum(x => x.ReturnAmount);
            loansByMonth.Add((int) Math.Ceiling(loans));
        }

        ViewBag.LoanLabels = (string) JsonSerializer.Serialize(months);
        ViewBag.LoanData = (string) JsonSerializer.Serialize(loansByMonth);

        return View();
    }

    // for profile detail page
    public IActionResult ProfileDetail()
    {
        var user = _context.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();


        ViewBag.UserName = user.UserName;
        ViewBag.Email = user.Email;
        ViewBag.FullName = user.FullName;
        ViewBag.UserRole = (from role in _context.Roles
            join userRole in _context.UserRoles on role.Id equals userRole.RoleId
            where userRole.UserId == user.Id
            select role.Name).FirstOrDefault();
        return View();
    }

    // to change password 

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ProfileDetail(ChangePassword model)
    {
        var user = _context.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();

        ViewBag.UserName = user.UserName;
        ViewBag.Email = user.Email;
        ViewBag.FullName = user.FullName;
        ViewBag.UserRole = (from role in _context.Roles
            join userRole in _context.UserRoles on role.Id equals userRole.RoleId
            where userRole.UserId == user.Id
            select role.Name).FirstOrDefault();

        if (!ModelState.IsValid) return View(model);


        var result = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);


        if (!result.Succeeded)
        {
            ModelState.AddModelError("", "Invalid Old Password");
            return View(model);
        }

        ViewBag.IsSuccess = true;
        ModelState.Clear();
        return View(model);
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

Controllers/IssueController.cs
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using HamroCarRental.Data;
using HamroCarRental.Models;
using HamroCarRental.Models.ViewModels;

namespace HamroCarRental.Controllers;

public class IssueController : Controller
{
    private readonly ApplicationDbContext _context;

    public IssueController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IEnumerable<IssueModel> GetAllAvailableCopy()
    {
        IEnumerable<IssueModel> loanRecord = from dt in _context.CarDetails
            join dtc in _context.CarCategories on dt.CategoryNumber equals dtc.CategoryNumber
            join dc in _context.carCopies on dt.CarNumber equals dc.CarNumber
            where dc.IsLoan == false
            select new IssueModel
            {
                CopyNumber = dc.CopyNumber,
                CarModel = dt.CarModel,
                CarCategory = dtc.CategoryName,
                AgeRestricted = dtc.AgeRestricted,
                DateReleased = dt.DateReleased
            };
        return loanRecord;
    }

    public IActionResult Index()
    {
        var availableCopy = GetAllAvailableCopy();

        ViewBag.AvailableCopyNumberList = JsonSerializer.Serialize(_context.carCopies.Where(x => x.IsLoan == false)
            .Select(x => x.CopyNumber).Distinct().ToList());

        return View(availableCopy);
    }

    // for search functionality
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Index(string request)
    {
        string CopyNumber = Request.Form["SearchCopyNumber"];
        ViewBag.SearchCopyNumber = CopyNumber;

        ViewBag.AvailableCopyNumberList = JsonSerializer.Serialize(_context.carCopies.Where(x => x.IsLoan == false)
            .Select(x => x.CopyNumber).Distinct().ToList());

        if (CopyNumber != null &&
            int.TryParse(CopyNumber, out var copyNumber) &&
            _context.carCopies.Where(x => x.CopyNumber == copyNumber).Count() > 0)
        {
            var loanRecord = from dt in _context.CarDetails
                join dtc in _context.CarCategories on dt.CategoryNumber equals dtc.CategoryNumber
                join dc in _context.carCopies on dt.CarNumber equals dc.CarNumber
                where dc.IsLoan == false && dc.CopyNumber == copyNumber
                select new IssueModel
                {
                    CopyNumber = dc.CopyNumber,
                    CarModel = dt.CarModel,
                    CarCategory = dtc.CategoryName,
                    AgeRestricted = dtc.AgeRestricted,
                    DateReleased = dt.DateReleased
                };
            return View(loanRecord);
        }

        if (CopyNumber == "")
        {
            var loanRecord = GetAllAvailableCopy();
            return View(loanRecord);
        }

        return View();
    }

    public IActionResult Create(int id)
    {
        if (id == 0 || _context.carCopies.Where(l => l.CopyNumber == id && l.IsLoan == false).Count() == 0)
            return RedirectToAction("Index");


        var currentLoan = (from dt in _context.CarDetails
            join dtc in _context.CarCategories on dt.CategoryNumber equals dtc.CategoryNumber
            join dc in _context.carCopies on dt.CarNumber equals dc.CarNumber
            where dc.CopyNumber == id
            select new IssueModel
            {
                CopyNumber = dc.CopyNumber,
                CarModel = dt.CarModel,
                CarCategory = dtc.CategoryName,
                AgeRestricted = dtc.AgeRestricted
            }).First();

        ViewData["MemberNumberList"] = from m in _context.Members
            select new SelectViewModel
                {SelectValue = m.MemberNumber, SelectKey = m.MemberFirstName + " " + m.MemberLastName};
        ViewData["LoanTypeList"] = from lt in _context.LoanTypes
            select new SelectViewModel {SelectValue = lt.LoanTypeNumber, SelectKey = lt.LoanTypeName};
        ViewData["Availablecar"] = currentLoan;
        ViewBag.CopyNumber = currentLoan.CopyNumber;
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create([Bind("LoanTypeNumber, CopyNumber, MemberNumber")] IssueModel rent)
    {
        var test = rent;

        var currentLoan = (from dt in _context.CarDetails
            join dtc in _context.CarCategories on dt.CategoryNumber equals dtc.CategoryNumber
            join dc in _context.carCopies on dt.CarNumber equals dc.CarNumber
            where dc.CopyNumber == rent.CopyNumber
            select new IssueModel
            {
                CopyNumber = dc.CopyNumber,
                CarModel = dt.CarModel,
                CarCategory = dtc.CategoryName,
                AgeRestricted = dtc.AgeRestricted
            }).First();

        ViewData["MemberNumberList"] = from m in _context.Members
            select new SelectViewModel
                {SelectValue = m.MemberNumber, SelectKey = m.MemberFirstName + " " + m.MemberLastName};
        ViewData["LoanTypeList"] = from lt in _context.LoanTypes
            select new SelectViewModel {SelectValue = lt.LoanTypeNumber, SelectKey = lt.LoanTypeName};
        ViewData["Availablecar"] = currentLoan;

        ViewBag.LoanTypeNumber = rent.LoanTypeNumber;
        ViewBag.MemberNumber = rent.MemberNumber;
        ViewBag.CopyNumber = rent.CopyNumber;

        string operation;
        try
        {
            operation = Request.Form["GenerateButton"];
        }
        catch
        {
            operation = "";
        }


        var ageRestriction = (from dc in _context.carCopies
            join d in _context.CarDetails on dc.CarNumber equals d.CarNumber
            join dtc in _context.CarCategories on d.CategoryNumber equals dtc.CategoryNumber
            where dc.CopyNumber == rent.CopyNumber
            select dtc.AgeRestricted).First();

        if (ageRestriction == "True" &&
            (DateTime.Today - _context.Members.Where(m => m.MemberNumber == rent.MemberNumber).First()
                .MemberDateOfBirth).Days / 365 < 18)
        {
            TempData["Error"] = "Below age restriction";
            return View();
        }


        var maxRentLimit = (from m in _context.Members
            join mt in _context.MembershipCategories on m.MemberCategoryNumber equals mt.MembershipCategoryNumber
            where m.MemberNumber == rent.MemberNumber
            select mt.MembershipCategoryTotalLoans).FirstOrDefault();

        if (_context.Loans.Where(l => l.DateReturn == DateTime.MinValue && l.MemberNumber == rent.MemberNumber)
                .Count() >= maxRentLimit)
        {
            TempData["Error"] = "Maximum number reached";
            return View();
        }


        var loanDays = (from lt in _context.LoanTypes
            where lt.LoanTypeNumber == rent.LoanTypeNumber
            select lt.Duration).First();

        var returnModel = (from dt in _context.CarDetails
            join dtc in _context.CarCategories on dt.CategoryNumber equals dtc.CategoryNumber
            join dc in _context.carCopies on dt.CarNumber equals dc.CarNumber
            where dc.CopyNumber == rent.CopyNumber
            select new ReturnModel
            {
                CopyNumber = dc.CopyNumber,
                CarModel = dt.CarModel,
                CarCategory = dtc.CategoryName,
                DateOut = DateTime.Today,
                DateDue = DateTime.Today.AddDays(loanDays),
                MemberName = _context.Members.Where(m => m.MemberNumber == rent.MemberNumber).First().MemberFirstName +
                             " " + _context.Members.Where(m => m.MemberNumber == rent.MemberNumber).First()
                                 .MemberLastName,
                StandardCharge = dt.StandardCharge,
                Payment = dt.StandardCharge * loanDays
            }).First();
        ViewData["RentalInformation"] = returnModel;

        if (operation != "Generate")
        {
            // to add new loan record
            var loan = new Loan
            {
                CopyNumber = rent.CopyNumber,
                MemberNumber = rent.MemberNumber,
                //LoanTypeNumber = rent.LoanTypeNumber,
                DateOut = DateTime.Today,
                DateDue = DateTime.Today.AddDays(loanDays),
                DateReturn = DateTime.MinValue,
                ReturnAmount = returnModel.Payment
            };
            _context.Loans.Add(loan);

            // Put the copy status to unavailable
            var Copy = _context.carCopies.Where(c => c.CopyNumber == rent.CopyNumber).First();
            Copy.IsLoan = true;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        return View();
    }
}

Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr/>
        <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home Page</a>
    </div>
</div>

Views/Shared/_AdminLayout.cshtml
@{
    var section = ViewData["Section"];
}

<html lang="en">

<head>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - HamroCarRental</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/fonts/iconic/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/nucleo-icons.css">
    <link rel="stylesheet" type="text/css" href="~/css/nucleo-svg.css">

    <link rel="stylesheet" type="text/css" href="~/css/argon-dashboard.css?v=2.0.2">

    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>

    @RenderSection("AddCustomStyles", false)

</head>

<body class="g-sidenav-show" style="background-color:#a689e1">

<!----------------------------------------Side Bar of Admin Panel -------------------------------------------------!>
<div class="min-height-300  position-absolute w-100" style="background:#a689e1"></div>
<aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
        <div class="col text-center mb-3 mt-4 mb-4">
            <a asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/images/logo-car-rental.png" class="navbar-brand-img h-200 max-height-100" alt="main_logo">              
            </a>
        </div>
    </div>

   
    <hr class="horizontal dark mt-4">

        
    <div class="">
        <ul class="navbar-nav ">
                 
            <li class="">
                <a class="nav-link "asp-controller="Admin" asp-action="Index">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="fa fa-chart-bar text-dark text-sm opacity-8 mb-1"></i>
                    </div>
                    <span class="nav-link-text ms-1">Dashboard</span>
                </a>
            </li>
            <li class="nav-item mt-3">
                <h6 class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6">Car Section</h6>
            </li>
            <li class="nav-item">
                <a class="nav-link " asp-controller="Issue" asp-action="Index">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="fa fa-film text-dark text-sm opacity-8 mb-1"></i>
                    </div>
                    <span class="nav-link-text ms-1"> Issue</span>
                </a>
            </li>
            

            <li class=" ">

                <a class="nav-link "asp-controller="Return" asp-action="Index">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="fa fa-ticket text-dark text-sm opacity-8 mb-1"></i>
                    </div>
                    <span class="nav-link-text ms-1">Return</span>
                </a>
            
            </li>
            <li class="nav-item">
                <a class="nav-link " asp-controller="CarDetails" asp-action="CarDetailsIndex">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="fa fa-list-alt text-dark text-sm opacity-8 mb-1"></i>
                    </div>
                    <span class="nav-link-text ms-1">Car Details</span>

                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link " asp-controller="CarDetails" asp-action="Create">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="fa fa-plus text-dark text-sm opacity-8 mb-1"></i>
                    </div>
                    <span class="nav-link-text ms-1">Add Car</span>

                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link " asp-controller="carCopies" asp-action="OlderThan365Days">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="fa fa-remove text-dark text-sm opacity-8 mb-1"></i>
                    </div>
                    <span class="nav-link-text ms-1">Old Car</span>

                </a>
            </li>


            <li class="nav-item mt-3">
                <h6 class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6">Members Section</h6>
            </li>

            <li class="nav-item">
                <a class="nav-link "asp-controller="Members" asp-action="Index">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="fa fa-info text-dark text-sm opacity-8 mb-1"></i>
                    </div>
                    <span class="nav-link-text ms-1">Member Details</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link "asp-controller="Members" asp-action="InactiveMembers">
                    <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="fa fa-list-alt text-dark text-sm opacity-8 mb-1"></i>
                    </div>
                    <span class="nav-link-text ms-1">Inactive Members</span>
                </a>
            </li>
                 <li class="nav-item">
                    <a class="nav-link "asp-controller="Members" asp-action="Index">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="fa fa-info text-dark text-sm opacity-8 mb-1"></i>
                        </div>
                        <span class="nav-link-text ms-1">Staff Details</span>
                    </a>
                </li>
                  
        </ul>
    </div>
    
</aside>

    <main class="main-content position-relative border-radius-lg "  style="background-color:#a689e1">
<!-- Navbar -->
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl " id="navbarBlur" data-scroll="false">
    <div class="container-fluid py-1 px-3">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                <li class="breadcrumb-item text-sm">
                    <a class="opacity-5 text-white" href="javascript:">Account</a>
                </li>
                <li class="breadcrumb-item text-sm text-white active" aria-current="page">Admin</li>
            </ol>

        </nav>

        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">

            <ul class="navbar-nav col  justify-content-end">

                <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                    <a href="javascript:" class="nav-link text-white p-0" id="iconNavbarSidenav">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line bg-white"></i>
                            <i class="sidenav-toggler-line bg-white"></i>
                            <i class="sidenav-toggler-line bg-white"></i>
                        </div>
                    </a>

                </li>

                <li class="nav-item dropdown pe-2 d-flex align-items-center">
                    <a href="javascript:" class="nav-link text-white p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-cog fixed-plugin-button-nav cursor-pointerr"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton" style="top:-0.74rem">

                        <li class="align-content-center">
                            <a class="dropdown-item border-radius-md" asp-area="" asp-controller="Admin" asp-action="ProfileDetail">
                                <div class="d-flex">
                                    <div class="my-auto pt-1">
                                        <i class="ni ni-single-02"></i>
                                    </div>
                                    <div class="d-flex flex-column">
                                        <h6 class="text-sm font-weight-normal my-auto">
                                            <span class="mx-2"></span>
                                            <span class="font-weight-bold">Profile</span>
                                        </h6>
                                    </div>
                                </div>
                            </a>
                        </li>

                        <li class="align-content-center">
                            <a class="dropdown-item border-radius-md" asp-area="" asp-controller="Authentication" asp-action="Logout">
                                <div class="d-flex">
                                    <div class="my-auto pt-1">
                                        <i class="ni ni-spaceship"></i>
                                    </div>
                                    <div class="d-flex flex-column">
                                        <h6 class="text-sm font-weight-normal my-auto">
                                            <span class="mx-2"></span>
                                            <span class="font-weight-bold">Log out</span>
                                        </h6>
                                    </div>
                                </div>
                            </a>
                        </li>


                    </ul>
                </li>

            </ul>
        </div>

    </div>
</nav>
<!-- End Navbar -->

@RenderBody()

</main>

<script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
<script src="~/js/core/popper.min.js"></script>
<script src="~/js/core/bootstrap.min.js"></script>
<script src="~/js/plugins/perfect-scrollbar.min.js"></script>
<script src="~/js/plugins/smooth-scrollbar.min.js"></script>
<script src="~/js/plugins/chartjs.min.js"></script>
<script src="~/js/plugins/bootstrap-notify.js"></script>
<script src="~/js/argon-dashboard.js.map"></script>

@await RenderSectionAsync("Scripts", false)
@RenderSection("AddCustomScripts", false)

<script>
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
<script src="~/js/argon-dashboard.min.js?v=2.0.2"></script>


</body>

</html>

Views/Shared/_CreateItem.cshtml
@model string;

@*@if (User.Identity.IsAuthenticated && User.IsInRole("AdminUser"))
{*@
<div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i> Add New
    </a>
</div>
@*}*@<a href="c:\users\dell\desktop\appdevcw2-sample-2022-HamroCarRental\views\shared\_createitem.cshtml">c:\users\dell\desktop\appdevcw2-sample-2022-HamroCarRental\views\shared\_createitem.cshtml</a>