Models/CarDetail.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using eTickets.Data.Base;

namespace HamroCarRental.Models;

public class CarDetail : IEntityBase
{
    [Key] public int CarNumber { get; set; }

    [Display(Name = "Category Number")]
    [ForeignKey("CategoryNumber")]
    public int CategoryNumber { get; set; }

    [Display(Name = "Studio Number")]
    [ForeignKey("StudioNumber")]
    public int StudioNumber { get; set; }

    [Display(Name = "Brand Number")]
    [ForeignKey("BrandNumber")]
    public int BrandNumber { get; set; }

    [Display(Name = "Car Picture")] public string CarPictureURL { get; set; }

    [Display(Name = "Car Model")] public string CarModel { get; set; }

    [Display(Name = "Release Date")] public DateTime DateReleased { get; set; }

    [Display(Name = "Standard Charge")] public decimal StandardCharge { get; set; }

    [Display(Name = "Penalty Charge")] public decimal PenaltyCharge { get; set; }

    //relationships
    public virtual CarCategory CarCategory { get; set; }
    public virtual Studio Studio { get; set; }
    public virtual Brand Brand { get; set; }

    //public ICollection<CastMember> CastMembers { get; set; }
    public ICollection<CarCopy> carCopies { get; set; }

    public string Description { get; internal set; }
}

Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using HamroCarRental.Data.Services;
using HamroCarRental.Models;

namespace HamroCarRental.Controllers;

public class BrandsController : Controller
{
    //injecting service to the controller
    private readonly IBrandsService _service;

    //defining a constructor
    public BrandsController(IBrandsService service)
    {
        _service = service;
    }

    //get Brand
    public async Task<IActionResult> Index()
    {
        var allBrands = await _service.GetAllAsync();
        return View(allBrands);
    }

    //Get: Brands/Create
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create([Bind("BrandPictureURL,BrandName")] Brand Brand)
    {
        await _service.AddAsync(Brand);
        return RedirectToAction(nameof(Index));
    }

    //Get: Brands/details/Id
    public async Task<IActionResult> Details(int id)
    {
        var BrandDetails = await _service.GetBrandAsync(id);

        if (BrandDetails == null) return View("NotFound");
        return View(BrandDetails);
    }

    //Get: Brands/edit
    public async Task<IActionResult> Edit(int id)
    {
        var BrandDetails = await _service.GetBrandAsync(id);
        if (BrandDetails == null) return View("NotFound");
        return View(BrandDetails);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, Brand Brand)
    {
        await _service.UpdateAsync(id, Brand);
        return RedirectToAction(nameof(Index));
    }

    //Get: Brands/delete
    public async Task<IActionResult> Delete(int id)
    {
        var BrandDetails = await _service.GetBrandAsync(id);
        if (BrandDetails == null) return View("NotFound");
        return View(BrandDetails);
    }

    [HttpPost]
    [ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var BrandDetails = await _service.GetBrandAsync(id);
        if (BrandDetails == null) return View("NotFound");

        await _service.DeleteAsync(id);
        return RedirectToAction(nameof(Index));
    }
}

Controllers/StudiosController.cs
using Microsoft.AspNetCore.Mvc;
using HamroCarRental.Data.Services;
using HamroCarRental.Models;

namespace HamroCarRental.Controllers;

public class StudiosController : Controller
{
    //injecting service to the controller
    private readonly IStudiosService _service;

    //creating a constructor
    public StudiosController(IStudiosService service)
    {
        _service = service;
    }

    //get Studio
    public async Task<IActionResult> Index()
    {
        var allStudios = await _service.GetAllAsync();
        return View(allStudios);
    }

    //Get: Brands/details/id
    public async Task<IActionResult> Details(int id)
    {
        var studioDetails = await _service.GetStudioAsync(id);

        if (studioDetails == null) return View("NotFound");
        return View(studioDetails);
    }

    //Get: CarCategories/Create
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create([Bind("StudioName")] Studio studio)
    {
        await _service.AddAsync(studio);
        return RedirectToAction(nameof(Index));
    }

    //Get: CarCategories/edit/id
    public async Task<IActionResult> Edit(int id)
    {
        var studioDetails = await _service.GetStudioAsync(id);
        if (studioDetails == null) return View("NotFound");
        return View(studioDetails);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, [Bind("StudioNumber, StudioName")] Studio studio)
    {
        if (id == studio.StudioNumber)
        {
            await _service.UpdateAsync(id, studio);
            return RedirectToAction(nameof(Index));
        }

        return View(studio);
    }

    //Get: Actors/delete/id
    public async Task<IActionResult> Delete(int id)
    {
        var studioDetails = await _service.GetStudioAsync(id);
        if (studioDetails == null) return View("NotFound");
        return View(studioDetails);
    }

    [HttpPost]
    [ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var studioDetails = await _service.GetStudioAsync(id);
        if (studioDetails == null) return View("NotFound");

        await _service.DeleteAsync(id);
        return RedirectToAction(nameof(Index));
    }
}

Views/CarDetails/CarDetailsIndex.cshtml
@{
    ViewData["Title"] = "CarDetailsIndex";
    Layout = "_AdminLayout";
}

<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header pb-0">
                    <h4 class="mt-3 text-center text-primary">Car Details</h4>
                    <hr/>
                </div>

                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center justify-content-center mb-0">
                            <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Car Title</th>
                                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7 ps-2">Date Released</th>
                                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7 ps-2">Brand</th>
                                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7 ps-2">Studio</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <div class="d-flex px-2 py-1">
                                            <div>
                                                <img src=@item.Picture class="avatar avatar-sm me-3" alt="user5">
                                            </div>
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-sm">@item.Title</h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <p class="text-xs font-weight-bold mb-0" style="margin-left: 1rem">@item.Release</p>
                                    </td>
                                    <td>
                                        <p class="text-xs font-weight-regular mb-0">@item.Brand</p>
                                    </td>
                                    <td>
                                        <p class="text-xs font-weight-regular mb-0">@item.Studio</p>
                                    </td>
                                    @*<td>
                                        @foreach (var value in item.Cast)
                                        {
                                            <p class="text-xs font-weight-regular mb-0">@value</p>
                                        }
                                    </td>*@
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

Views/CarDetails/Create.cshtml
@model newCarDetailVM
@using HamroCarRental.Data;

@{
    ViewData["Title"] = "Insert a new Car Title";
    Layout = "_AdminLayout";
}

<div class="container-fluid py-4">

<div class="card mb-4">

    <div class="card-header pb-0">
        <h4 class="mt-3 mb-2 text-center text-primary">Insert New car</h4>
        <hr>
    </div>

    <div class="card-body px-2 pt-0 pb-2 mt-3">

        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row">

                <div class="col">
                    <ul class="list-group">
                        <li class="list-group-item border-0 d-flex justify-content-start ps-0 mb-2 ">
                            <div class="d-flex flex-column ">
                                <p asp-for="CarModel" class="mb-1 text-secondary font-weight-bold text-md ms-4 mt-2 me-4">Car Title:</p>
                            </div>
                            <div class="p-2 input-group-sm ms-6">
                                <input asp-for="CarModel" type="text" class="form-control">
                            </div>
                        </li>
                    </ul>
                    <ul class="list-group">
                        <li class="list-group-item border-0 d-flex justify-content-start ps-0 mb-2">
                            <div class="d-flex flex-column">
                                <p asp-for="DateReleased" class="mb-1 text-secondary font-weight-bold text-md ms-4 mt-2 me-2">Release Date:</p>
                            </div>
                            <div class="p-2 input-group-sm ms-5">
                                <input asp-for="DateReleased" type="date" class="form-control">
                            </div>
                        </li>
                    </ul>
                    <ul class="list-group">
                        <li class="list-group-item border-0 d-flex justify-content-start ps-0  border-radius-lg ">
                            <div class="d-flex flex-column">
                                <h6 asp-for="CategoryNumber" class="mb-1 text-secondary font-weight-bold text-md ms-4 mt-3">Car Category:</h6>
                            </div>
                            <div class="dropdown p-2 ">
                                <select asp-for="CategoryNumber" asp-items="ViewBag.CarCategories" class="btn btn-outline-secondary dropdown-toggle px-7 py-2 ms-5" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                                    Choose
                                </select>
                            </div>
                            <div class="p-2 me-1">
                                <a class="btn btn-secondary opacity-7 btn mt-1" asp-controller="CarCategories" asp-action="Create">
                                    <i class="fas fa-plus" style="color:white" aria-hidden="true"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                    <ul class="list-group">
                        <li class="list-group-item border-0 d-flex justify-content-start ps-0  border-radius-lg">
                            <div class="d-flex flex-column">
                                <h6 asp-for="StudioNumber" class="mb-1 text-secondary font-weight-bold text-md ms-4 mt-3">Car Studio:</h6>
                            </div>
                            <div class="dropdown p-2">
                                <select asp-for="StudioNumber" asp-items="ViewBag.Studios" class="btn btn-outline-secondary dropdown-toggle px-7 py-2 ms-6" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                                    Choose
                                </select>
                            </div>
                            <div class="p-2 me-1">
                                <a asp-controller="Studios" asp-action="Create" class="btn btn-secondary  opacity-7 btn mt-1">
                                    <i class="fas fa-plus" style="color:white" aria-hidden="true"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                    <ul class="list-group">
                        <li class="list-group-item border-0 d-flex justify-content-start ps-0  border-radius-lg">
                            <div class="d-flex flex-column">
                                <h6 asp-for="BrandNumber" class="mb-1 text-secondary font-weight-bold text-md ms-4 mt-3">Brand:</h6>
                            </div>
                            <div class="dropdown p-2">
                                <select asp-for="BrandNumber" asp-items="ViewBag.Brands" class="btn btn-outline-secondary dropdown-toggle px-7 py-2 ms-6" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                                    Choose
                                </select>
                            </div>
                            <div class="p-2 me-1">
                                <a asp-controller="Brands" asp-action="Create" class="btn btn-secondary  opacity-7 btn mt-1">
                                    <i class="fas fa-plus" style="color:white" aria-hidden="true"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                  @*  <ul class="list-group">
                        <li class="list-group-item border-0 d-flex justify-content-start ps-0  border-radius-lg">
                            <div class="d-flex flex-column">
                                <h6 asp-for="ActorNumbers" class="mb-1 text-secondary font-weight-bold text-md ms-4 mt-3">Cast Members:</h6>
                            </div>
                            <div class="dropdown p-2">
                                <select asp-for="ActorNumbers" class="form-control" asp-items="ViewBag.Actors" multiple class="btn btn-outline-secondary dropdown-toggle px-7 py-2 " style="margin-left: 2.8rem;" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                                    Choose
                                </select>
                            </div>
                            <div class="p-2 me-1">
                                <a asp-controller="Actors" asp-action="Create" class="btn btn-secondary opacity-7 btn mt-1">
                                    <i class="fas fa-plus" style="color:white" aria-hidden="true"></i>
                                </a>
                            </div>
                        </li>
                    </ul>*@
                    <ul class="list-group">
                        <li class="list-group-item border-0 d-flex justify-content-start ps-0 mb-2">
                            <div class="d-flex flex-column">
                                <p asp-for="StandardCharge" class="mb-1 text-secondary font-weight-bold text-md ms-4 mt-2 me-2">Standard Charge:</p>
                            </div>
                            <div class="p-2 input-group-sm ms-3">
                                <input asp-for="StandardCharge" type="number" class="form-control">
                            </div>
                        </li>
                    </ul>
                    <ul class="list-group">
                        <li class="list-group-item border-0 d-flex justify-content-start ps-0 mb-2">
                            <div class="d-flex flex-column">
                                <p asp-for="PenaltyCharge" class="mb-1 text-secondary font-weight-bold text-md ms-4 mt-2 me-2">Penalty Charge:</p>
                            </div>
                            <div class="p-2 input-group-sm ms-4">
                                <input asp-for="PenaltyCharge" type="number" type="text" class="form-control">
                            </div>
                        </li>
                    </ul>
                </div>


                <div class="col">
                    <ul class="list-group">
                        <li class="list-group-item border-0 d-flex justify-content-start ps-0 mb-4 border-radius-lg">
                            <div class="d-flex flex-column">
                                <h6 asp-for="CarPictureURL" class="mb-1 text-secondary font-weight-bold text-md ms-4 mt-2 me-2">Image Link:</h6>
                            </div>
                            <div class="p-2 input-group-sm ms-4" style=" width: 55%">
                                <input asp-for="CarPictureURL" class="form-control"/>
                            </div>
                        </li>
                    </ul>

                    <div class="ms-9">
                        <img id="ImageUrlPreview" style="height:60vh;"/>
                    </div>
                </div>

                <!-- buttons -->
                <div class="d-flex  flex-row-reverse mt-4" style="margin-right:5vh">
                    <div class=" justify-content-center">
                        <input type="submit" value="Create" class="btn btn-primary  btn-md px-5">
                    </div>
                    <div class="justify-content-center mx-4">
                        <a class="btn btn-outline-secondary" asp-action="Index" class="btn btn-outline-danger btn-md px-5">
                            Show All
                        </a>
                    </div>
                </div>


            </div>
        </form>

    </div>

</div>

@section Scripts{
    <script>
        $("#CarPictureURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

Views/CarDetails/Details.cshtml
@model CarDetail

@{
    ViewData["Title"] = "car details";
    Layout = "_AdminLayout";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.CarModel
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.CarPictureURL" width="100%" alt="@Model.CarModel">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="Studios" asp-action="Details" asp-route-id="@Model.StudioNumber">
                                @Model.Studio.StudioName
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Category: </b>
                            <a asp-controller="CarCategories" asp-action="Details" asp-route-id="@Model.CategoryNumber">
                                @Model.CarCategory.CategoryName
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Brand: </b>
                            <a asp-controller="Brands" asp-action="Details" asp-route-id="@Model.BrandNumber">
                                @Model.Brand.BrandName
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Date Released: </b>@Model.DateReleased.ToString("dd MMM yy")
                        </p>
                        <p class="card-text"><b>Standard Charge </b>Rs. @Model.StandardCharge</p>
                        <p class="card-text"><b>Penalty Charge </b>Rs. @Model.PenaltyCharge</p>
                      @*  <p class="card-text">
                            <b>Actors: </b>
                            <hr/>
                            <div class="row">
                                @foreach (var actor in Model.CastMembers)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="@actor.Actor.ActorPictureURL" style="max-width: 150px"/>
                                        <br/>
                                        <a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.ActorNumber">@actor.Actor.ActorFirstName @actor.Actor.ActorSurname</a>
                                    </div>
                                }
                            </div>
                        </p>*@

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/CarDetails/Edit.cshtml
@model newCarDetailVM
@using HamroCarRental.Data;

@{
    ViewData["Title"] = "Update Car Title";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Update Car Title</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <input type="hidden" asp-for="CarNumber"/>
                            <div class="form-group">
                                <label asp-for="CarModel" class="control-label"></label>
                                <input asp-for="CarModel" class="form-control"/>
                                <span asp-validation-for="CarModel" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DateReleased" class="control-label"></label>
                                <input asp-for="DateReleased" type="date" class="form-control"/>
                                <span asp-validation-for="DateReleased" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StandardCharge" class="control-label"></label>
                                <input asp-for="StandardCharge" type="number" class="form-control"/>
                                <span asp-validation-for="StandardCharge" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PenaltyCharge" class="control-label"></label>
                                <input asp-for="PenaltyCharge" type="number" class="form-control"/>
                                <span asp-validation-for="PenaltyCharge" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CarPictureURL" class="control-label"></label>
                                <input asp-for="CarPictureURL" class="form-control"/>
                                <span asp-validation-for="CarPictureURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="StudioNumber" class="control-label"></label>
                                <select asp-for="StudioNumber" class="form-control" asp-items="ViewBag.Studios"></select>
                                <span asp-validation-for="StudioNumber" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CategoryNumber" class="control-label"></label>
                                <select asp-for="CategoryNumber" class="form-control" asp-items="ViewBag.CarCategories"></select>
                                <span asp-validation-for="CategoryNumber" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="BrandNumber" class="control-label"></label>
                                <select asp-for="BrandNumber" class="form-control" asp-items="ViewBag.Brands"></select>
                                <span asp-validation-for="BrandNumber" class="text-danger"></span>
                            </div>
                          @*  <div class="form-group">
                                <label asp-for="ActorNumbers" class="control-label"></label>

                                <select asp-for="ActorNumbers" class="form-control" asp-items="ViewBag.Actors" multiple></select>
                                <span asp-validation-for="ActorNumbers" class="text-danger"></span>
                            </div>*@
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview"/>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right"/>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function (){
            var output = document.getElementById("ImageUrlPreview");
            output.src = $("#CarPictureURL").val();
        })

        $("#CarPictureURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

Views/CarDetails/Index.cshtml
@*Define model*@

@model IEnumerable<CarDetail>

@{
    ViewData["Title"] = "Cars";
}


@*Define ViewData*@

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.CarModel
                                    <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.CarNumber">
                                        <i class="bi bi-pencil-square"></i>
                                    </a>
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.CarPictureURL" width="100%" alt="@item.CarModel">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">
                                <b>Studio: </b>@item.Studio.StudioName
                            </p>
                            <p class="card-text">
                                <b>Category: </b>@item.CarCategory.CategoryName
                            </p>
                            <p class="card-text">
                                <b>Brand: </b>@item.Brand.BrandName
                            </p>
                            <p class="card-text">
                                <b>Date Released: </b>@item.DateReleased.ToString("dd MMM yy")
                            </p>
                            <p class="card-text"><b>Standard Charge </b>Rs. @item.StandardCharge</p>
                            <p class="card-text"><b>Penalty Charge </b>Rs. @item.PenaltyCharge</p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.CarNumber">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_CreateItem", "CarDetails")